version: "3"

services:

  mqtt:
    image: docker.io/library/eclipse-mosquitto:2.0.11
    ports:
      - "18830:18830"
    restart: on-failure
    volumes:
      - ./vmc/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  vio-expiremental:
    depends_on:
      - mqtt
    image: vio-experimental:v1
    privileged: true
    restart: on-failure

  # sandbox:
  #   depends_on:
  #     - mqtt
  #   build: vrc_sandbox
  #   restart: on-failure
